# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            North County San Diego Investment Club
tagline:          'A place to learn and drink beer'
description:      'A place to learn and drink beer. The Site credits the Lanyon Theme by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'Nathan Wells'
  url:            https://ngwells.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://ncsdinvestmentclub.github.io
